### ISSUE TITLE
Final Launch checklist :rocket: 

### ISSUE THREAD

**Issue by gichiba** [ethereum/nxbn-website#130]
- [x] Correct lat/long locations (#129)
- [x] Finalize map textures (@nloureiro )
- [x] Fix button label issues ("know more") @gichiba 
- [x] [[Fellowship Story Archive (website)]] @gichiba 
- [x] [[Next Billion Website Text]] @gichiba 
    - [x] Scholars FAQ
    - [x] Fellows FAQ
    - [x] Team
- [x] headshots (black and white filter)
- [x] tag colors @nloureiro 
- [x] review hero transitions
- [x] New 'about' images (representation, maybe (nice to have) ) 

## Scholars

- [x] fix hero thing @nloureiro 
- [x] Get updated info on new scholars copy/program stuff @gichiba 
- [x] unique copy for past devcon events @gichiba

**Comment by nloureiro** [comment]
@gichiba, on the map texture, I changed a little bit, I'm not sure what else can be done here...
