### ISSUE TITLE
Home page

### ISSUE THREAD

**Issue by gichiba** [ethereum/nxbn-website#88]
This is a list of all changes and things for the home page:

- [x] Rethink design of hero text
- [ ] Add real locations of fellows to map
- [ ] Tweak the heashots and label of the map to be a little bigger and to crop headshots instead of stretch. 
- [x] tweak font sizes for the different sections (and update site-wide)

```[tasklist]
### Tasks
```

**Comment by gichiba** [comment]
- [ ] Change devcon image
- [ ] Add tree to home page; smooth out the seams from top to bottom
- [ ] @corwintines to make the links work for blogposts
- [ ] Window sizing bugs with earth and hero (needs to stay constrained to the center)
